#!/bin/bash
echo "Welcome to the Velyst E-Ink Interactive Terminal!"
echo "------------------------------------------------"
echo "This terminal supports interactive buttons via the [BTN:id:label] syntax."
echo ""
echo "Try clicking one of the buttons below:"
echo ""
echo "[BTN:ls:List Files]  [BTN:pwd:Print Directory]  [BTN:whoami:Who Am I]"
echo ""
echo "When you click a button, its ID is sent to the shell as a command."
